# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: build node docker images
  block:
  - name: create temporary custom .openness_gitconfig
    include_tasks: ../../../git_repo/tasks/gitconfig_bootstrap.yml
  - name: binaries and images
    shell: source /etc/profile && GOPATH={{ _gopath }} make onprem-{{ onprem_dataplane }}
    args:
      chdir: "{{ _git_repo_dest }}"
  always:
  - name: remove temporary .openness_gitconfig
    include_tasks: ../../../git_repo/tasks/gitconfig_remove.yml
